version: '2'
services:
  xunsearch-zx:
    build: ./dev/xunsearch/
    volumes:
      - ./dev/xunsearch/data:/usr/local/xunsearch/data
    # restart: always
  redis-zx:
    build: ./dev/redis/
    volumes:
      - ./dev/redis/data:/data
    # restart: always
    command: redis-server
  php-fpm-zx:
    build: ./dev/php/
    depends_on:
      - mysql-db-zx
      - redis-zx
      - xunsearch-zx
    links:
      - mysql-db-zx:mysql-db-zx
      - redis-zx:redis-zx
      - xunsearch-zx:xunsearch-zx
    environment:
      DATABASE_LOCALHOST: mysql-db-zx
      DATABASE_NAME     : zhenxiang
      DATABASE_USERNAME : admin
      DATABASE_PASSWORD : d8574a472c266986d441b242010f9313
      REDIS_LOCALHOST   : redis-zx
      XUNSEARCH_LOCALHOST: xunsearch-zx:8383
      XUNSEARCH_LOCALHOST2: xunsearch-zx:8484
    volumes:
      - ./:/data/www:rw
      - ./dev/php/php.ini:/usr/local/etc/php/php.ini:ro
    # restart: always
    command: php-fpm
  nginx-zx:
    build: ./dev/nginx
    depends_on:
      - php-fpm-zx
    links:
      - php-fpm-zx:php-fpm-zx
    volumes:
      - ./:/data/www:rw
      - ./dev/nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dev/nginx/logs:/var/log/nginx
    ports:
      - "8880:80"
      - "8443:443"
    # restart: always
    command: nginx -g 'daemon off;'
  mysql-db-zx:
    build: ./dev/mysql
    # ports:
    #   - "3306:3306"
    volumes:
      - ./dev/mysql/data:/var/lib/mysql:rw
      - ./dev/mysql/logs:/var/lib/mysql-logs:rw
      - ./dev/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 070050
      MYSQL_DATABASE: zhenxiang
      MYSQL_USER: admin
      MYSQL_PASSWORD: d8574a472c266986d441b242010f9313
    # restart: always
    command: "--character-set-server=utf8"